name: Distracted by Squirrels
markdown: redcarpet
include: [.htaccess]
exclude: [package.json ,Gruntfile.js, bower.json, node_modules, README.md, LICENSE]

permalink: /:categories/:title.html

mode: production
